import type { ScanResult } from "./auth";

export function downloadReport(scan: ScanResult, patientName: string, patientEmail: string) {
  const html = `<!doctype html><html><head><meta charset="utf-8"/><title>PinkShield Report ${scan.id}</title>
<style>
  body { font-family: 'Inter', system-ui, sans-serif; margin: 0; padding: 40px; color: #2a1530; background: #fff; }
  .header { display:flex; justify-content:space-between; align-items:center; border-bottom: 3px solid #d63384; padding-bottom: 16px; margin-bottom: 28px; }
  .logo { font-size: 28px; font-weight: 800; background: linear-gradient(135deg,#d63384,#f78fb3); -webkit-background-clip: text; color: transparent; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .meta { display:grid; grid-template-columns: repeat(2, 1fr); gap: 12px; background: #fdf2f8; padding: 16px; border-radius: 10px; margin-bottom: 24px; }
  .meta div b { display:block; font-size: 11px; color:#9b4072; text-transform:uppercase; letter-spacing:0.05em; margin-bottom:2px; }
  .risk { display:inline-block; padding: 6px 14px; border-radius: 999px; font-weight:700; font-size:14px; }
  .risk.normal { background:#d1fadf; color:#067647; }
  .risk.low { background:#fef3c7; color:#92400e; }
  .risk.medium { background:#ffedd5; color:#c2410c; }
  .risk.high, .risk.critical { background:#fee2e2; color:#b91c1c; }
  h2 { font-size: 15px; margin: 22px 0 8px; color:#9b4072; text-transform:uppercase; letter-spacing:0.05em; }
  ul { padding-left: 20px; line-height: 1.7; }
  .footer { margin-top: 50px; padding-top: 16px; border-top: 1px solid #e5d4dd; font-size: 11px; color:#666; }
</style></head><body>
<div class="header">
  <div><div class="logo">PinkShield</div><div style="font-size:12px;color:#666;">AI-Powered Breast Cancer Detection Report</div></div>
  <div style="text-align:right;font-size:12px;color:#666;">Report ID<br/><b style="color:#2a1530;">${scan.id}</b></div>
</div>
<h1>Diagnostic Summary</h1>
<div class="meta">
  <div><b>Patient</b>${patientName}</div>
  <div><b>Email</b>${patientEmail}</div>
  <div><b>Scan Date</b>${new Date(scan.date).toLocaleString()}</div>
  <div><b>AI Confidence</b>${scan.confidence}%</div>
  <div><b>Risk Classification</b><span class="risk ${scan.risk.toLowerCase().split(" ")[0]}">${scan.risk}</span></div>
  <div><b>Generated</b>${new Date().toLocaleString()}</div>
</div>
<h2>AI Analysis Summary</h2>
<p>${scan.summary}</p>
<h2>Recommendations</h2>
<ul>${scan.recommendations.map((r) => `<li>${r}</li>`).join("")}</ul>
<h2>Important Note</h2>
<p style="font-size:13px;line-height:1.6;">This report is generated by an AI-assisted screening model and is intended for informational purposes only. It does not constitute a medical diagnosis. Please consult a qualified oncologist or radiologist for clinical confirmation, additional imaging, and treatment planning.</p>
<div class="footer">© PinkShield Healthcare · Awareness Saves Lives · care@pinkshield.health · Helpline 1800-PINK-911</div>
<script>setTimeout(()=>window.print(),300);</script>
</body></html>`;
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const w = window.open(url, "_blank");
  if (!w) {
    const a = document.createElement("a");
    a.href = url;
    a.download = `pinkshield-report-${scan.id}.html`;
    a.click();
  }
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
