/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentRouteImport } from './routes/treatment'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PreventionRouteImport } from './routes/prevention'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AiDetectionRouteImport } from './routes/ai-detection'
import { Route as AboutCancerRouteImport } from './routes/about-cancer'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const TreatmentRoute = TreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventionRoute = PreventionRouteImport.update({
  id: '/prevention',
  path: '/prevention',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDetectionRoute = AiDetectionRouteImport.update({
  id: '/ai-detection',
  path: '/ai-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutCancerRoute = AboutCancerRouteImport.update({
  id: '/about-cancer',
  path: '/about-cancer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-cancer': typeof AboutCancerRoute
  '/ai-detection': typeof AiDetectionRoute
  '/login': typeof LoginRoute
  '/prevention': typeof PreventionRoute
  '/signup': typeof SignupRoute
  '/treatment': typeof TreatmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-cancer': typeof AboutCancerRoute
  '/ai-detection': typeof AiDetectionRoute
  '/login': typeof LoginRoute
  '/prevention': typeof PreventionRoute
  '/signup': typeof SignupRoute
  '/treatment': typeof TreatmentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about-cancer': typeof AboutCancerRoute
  '/ai-detection': typeof AiDetectionRoute
  '/login': typeof LoginRoute
  '/prevention': typeof PreventionRoute
  '/signup': typeof SignupRoute
  '/treatment': typeof TreatmentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-cancer'
    | '/ai-detection'
    | '/login'
    | '/prevention'
    | '/signup'
    | '/treatment'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-cancer'
    | '/ai-detection'
    | '/login'
    | '/prevention'
    | '/signup'
    | '/treatment'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-cancer'
    | '/ai-detection'
    | '/login'
    | '/prevention'
    | '/signup'
    | '/treatment'
    | '/_authenticated/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutCancerRoute: typeof AboutCancerRoute
  AiDetectionRoute: typeof AiDetectionRoute
  LoginRoute: typeof LoginRoute
  PreventionRoute: typeof PreventionRoute
  SignupRoute: typeof SignupRoute
  TreatmentRoute: typeof TreatmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatment': {
      id: '/treatment'
      path: '/treatment'
      fullPath: '/treatment'
      preLoaderRoute: typeof TreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevention': {
      id: '/prevention'
      path: '/prevention'
      fullPath: '/prevention'
      preLoaderRoute: typeof PreventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-detection': {
      id: '/ai-detection'
      path: '/ai-detection'
      fullPath: '/ai-detection'
      preLoaderRoute: typeof AiDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-cancer': {
      id: '/about-cancer'
      path: '/about-cancer'
      fullPath: '/about-cancer'
      preLoaderRoute: typeof AboutCancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutCancerRoute: AboutCancerRoute,
  AiDetectionRoute: AiDetectionRoute,
  LoginRoute: LoginRoute,
  PreventionRoute: PreventionRoute,
  SignupRoute: SignupRoute,
  TreatmentRoute: TreatmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
