/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTreatmentRouteImport } from './routes/_authenticated/treatment'
import { Route as AuthenticatedPreventionRouteImport } from './routes/_authenticated/prevention'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAiDetectionRouteImport } from './routes/_authenticated/ai-detection'
import { Route as AuthenticatedAboutCancerRouteImport } from './routes/_authenticated/about-cancer'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTreatmentRoute = AuthenticatedTreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreventionRoute = AuthenticatedPreventionRouteImport.update({
  id: '/prevention',
  path: '/prevention',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiDetectionRoute =
  AuthenticatedAiDetectionRouteImport.update({
    id: '/ai-detection',
    path: '/ai-detection',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAboutCancerRoute =
  AuthenticatedAboutCancerRouteImport.update({
    id: '/about-cancer',
    path: '/about-cancer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about-cancer': typeof AuthenticatedAboutCancerRoute
  '/ai-detection': typeof AuthenticatedAiDetectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/prevention': typeof AuthenticatedPreventionRoute
  '/treatment': typeof AuthenticatedTreatmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/about-cancer': typeof AuthenticatedAboutCancerRoute
  '/ai-detection': typeof AuthenticatedAiDetectionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/prevention': typeof AuthenticatedPreventionRoute
  '/treatment': typeof AuthenticatedTreatmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/about-cancer': typeof AuthenticatedAboutCancerRoute
  '/_authenticated/ai-detection': typeof AuthenticatedAiDetectionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/prevention': typeof AuthenticatedPreventionRoute
  '/_authenticated/treatment': typeof AuthenticatedTreatmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/about-cancer'
    | '/ai-detection'
    | '/dashboard'
    | '/prevention'
    | '/treatment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/about-cancer'
    | '/ai-detection'
    | '/dashboard'
    | '/prevention'
    | '/treatment'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/about-cancer'
    | '/_authenticated/ai-detection'
    | '/_authenticated/dashboard'
    | '/_authenticated/prevention'
    | '/_authenticated/treatment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/treatment': {
      id: '/_authenticated/treatment'
      path: '/treatment'
      fullPath: '/treatment'
      preLoaderRoute: typeof AuthenticatedTreatmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prevention': {
      id: '/_authenticated/prevention'
      path: '/prevention'
      fullPath: '/prevention'
      preLoaderRoute: typeof AuthenticatedPreventionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-detection': {
      id: '/_authenticated/ai-detection'
      path: '/ai-detection'
      fullPath: '/ai-detection'
      preLoaderRoute: typeof AuthenticatedAiDetectionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/about-cancer': {
      id: '/_authenticated/about-cancer'
      path: '/about-cancer'
      fullPath: '/about-cancer'
      preLoaderRoute: typeof AuthenticatedAboutCancerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAboutCancerRoute: typeof AuthenticatedAboutCancerRoute
  AuthenticatedAiDetectionRoute: typeof AuthenticatedAiDetectionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPreventionRoute: typeof AuthenticatedPreventionRoute
  AuthenticatedTreatmentRoute: typeof AuthenticatedTreatmentRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAboutCancerRoute: AuthenticatedAboutCancerRoute,
  AuthenticatedAiDetectionRoute: AuthenticatedAiDetectionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPreventionRoute: AuthenticatedPreventionRoute,
  AuthenticatedTreatmentRoute: AuthenticatedTreatmentRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
